In [17]:
import pandas as pd

In [18]:
obesityDataSet = pd.read_csv('ObesityDataSet_raw_and_data_sinthetic.csv', sep=',')

obesityDataSet.shape

(2111, 17)

In [19]:
obesityDataSet.head

<bound method NDFrame.head of             Age  Gender    Height      Weight        CALC FAVC  FCVC  NCP  \
0     21.000000  Female  1.620000   64.000000          no   no   2.0  3.0
1     21.000000  Female  1.520000   56.000000   Sometimes   no   3.0  3.0
2     23.000000    Male  1.800000   77.000000  Frequently   no   2.0  3.0
3     27.000000    Male  1.800000   87.000000  Frequently   no   3.0  3.0
4     22.000000    Male  1.780000   89.800000   Sometimes   no   2.0  1.0
...         ...     ...       ...         ...         ...  ...   ...  ...
2106  20.976842  Female  1.710730  131.408528   Sometimes  yes   3.0  3.0
2107  21.982942  Female  1.748584  133.742943   Sometimes  yes   3.0  3.0
2108  22.524036  Female  1.752206  133.689352   Sometimes  yes   3.0  3.0
2109  24.361936  Female  1.739450  133.346641   Sometimes  yes   3.0  3.0
2110  23.664709  Female  1.738836  133.472641   Sometimes  yes   3.0  3.0

      SCC SMOKE      CH2O family_history_with_overweight       FAF       TUE  \
0      no    no  2.000000                            yes  0.000000  1.000000
1     yes   yes  3.000000                            yes  3.000000  0.000000
2      no    no  2.000000                            yes  2.000000  1.000000
3      no    no  2.000000                             no  2.000000  0.000000
4      no    no  2.000000                             no  0.000000  0.000000
...   ...   ...       ...                            ...       ...       ...
2106   no    no  1.728139                            yes  1.676269  0.906247
2107   no    no  2.005130                            yes  1.341390  0.599270
2108   no    no  2.054193                            yes  1.414209  0.646288
2109   no    no  2.852339                            yes  1.139107  0.586035
2110   no    no  2.863513                            yes  1.026452  0.714137

           CAEC                 MTRANS           NObeyesdad
0     Sometimes  Public_Transportation        Normal_Weight
1     Sometimes  Public_Transportation        Normal_Weight
2     Sometimes  Public_Transportation        Normal_Weight
3     Sometimes                Walking   Overweight_Level_I
4     Sometimes  Public_Transportation  Overweight_Level_II
...         ...                    ...                  ...
2106  Sometimes  Public_Transportation     Obesity_Type_III
2107  Sometimes  Public_Transportation     Obesity_Type_III
2108  Sometimes  Public_Transportation     Obesity_Type_III
2109  Sometimes  Public_Transportation     Obesity_Type_III
2110  Sometimes  Public_Transportation     Obesity_Type_III

[2111 rows x 17 columns]>

In [20]:
display(obesityDataSet)

obesityDataSet.dtypes

,Age,Gender,Height,Weight,CALC,FAVC,FCVC,NCP,SCC,SMOKE,CH2O,family_history_with_overweight,FAF,TUE,CAEC,MTRANS,NObeyesdad
0,21.000000,Female,1.620000,64.000000,no,no,2.0,3.0,no,no,2.000000,yes,0.000000,1.000000,Sometimes,Public_Transportation,Normal_Weight
1,21.000000,Female,1.520000,56.000000,Sometimes,no,3.0,3.0,yes,yes,3.000000,yes,3.000000,0.000000,Sometimes,Public_Transportation,Normal_Weight
2,23.000000,Male,1.800000,77.000000,Frequently,no,2.0,3.0,no,no,2.000000,yes,2.000000,1.000000,Sometimes,Public_Transportation,Normal_Weight
3,27.000000,Male,1.800000,87.000000,Frequently,no,3.0,3.0,no,no,2.000000,no,2.000000,0.000000,Sometimes,Walking,Overweight_Level_I
4,22.000000,Male,1.780000,89.800000,Sometimes,no,2.0,1.0,no,no,2.000000,no,0.000000,0.000000,Sometimes,Public_Transportation,Overweight_Level_II
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2106,20.976842,Female,1.710730,131.408528,Sometimes,yes,3.0,3.0,no,no,1.728139,yes,1.676269,0.906247,Sometimes,Public_Transportation,Obesity_Type_III
2107,21.982942,Female,1.748584,133.742943,Sometimes,yes,3.0,3.0,no,no,2.005130,yes,1.341390,0.599270,Sometimes,Public_Transportation,Obesity_Type_III
2108,22.524036,Female,1.752206,133.689352,Sometimes,yes,3.0,3.0,no,no,2.054193,yes,1.414209,0.646288,Sometimes,Public_Transportation,Obesity_Type_III
2109,24.361936,Female,1.739450,133.346641,Sometimes,yes,3.0,3.0,no,no,2.852339,yes,1.139107,0.586035,Sometimes,Public_Transportation,Obesity_Type_III
2110,23.664709,Female,1.738836,133.472641,Sometimes,yes,3.0,3.0,no,no,2.863513,yes,1.026452,0.714137,Sometimes,Public_Transportation,Obesity_Type_III

Age                               float64
Gender                             object
Height                            float64
Weight                            float64
CALC                               object
FAVC                               object
FCVC                              float64
NCP                               float64
SCC                                object
SMOKE                              object
CH2O                              float64
family_history_with_overweight     object
FAF                               float64
TUE                               float64
CAEC                               object
MTRANS                             object
NObeyesdad                         object
dtype: object

In [21]:
obesityDataSet.isnull().sum()

Age                               0
Gender                            0
Height                            0
Weight                            0
CALC                              0
FAVC                              0
FCVC                              0
NCP                               0
SCC                               0
SMOKE                             0
CH2O                              0
family_history_with_overweight    0
FAF                               0
TUE                               0
CAEC                              0
MTRANS                            0
NObeyesdad                        0
dtype: int64

In [26]:
obesityTypeDataSet = obesityDataSet.loc[(obesityDataSet['NObeyesdad'] != 'Normal_Weight') & (obesityDataSet['NObeyesdad'] != 'Overweight_Level_I') & (obesityDataSet['NObeyesdad'] != 'Overweight_Level_I') & (obesityDataSet['NObeyesdad'] != 'Overweight_Level_II')]
display(obesityTypeDataSet)

,Age,Gender,Height,Weight,CALC,FAVC,FCVC,NCP,SCC,SMOKE,CH2O,family_history_with_overweight,FAF,TUE,CAEC,MTRANS,NObeyesdad
10,26.000000,Male,1.850000,105.000000,Sometimes,yes,3.0,3.0,no,no,3.000000,yes,2.000000,2.000000,Frequently,Public_Transportation,Obesity_Type_I
13,41.000000,Male,1.800000,99.000000,Frequently,yes,2.0,3.0,no,no,2.000000,no,2.000000,1.000000,Sometimes,Automobile,Obesity_Type_I
17,29.000000,Female,1.530000,78.000000,no,yes,2.0,1.0,no,no,2.000000,no,0.000000,0.000000,Sometimes,Automobile,Obesity_Type_I
21,52.000000,Female,1.690000,87.000000,no,yes,3.0,1.0,no,yes,2.000000,yes,0.000000,0.000000,Sometimes,Automobile,Obesity_Type_I
23,22.000000,Female,1.600000,82.000000,Sometimes,yes,1.0,1.0,no,no,2.000000,yes,0.000000,2.000000,Sometimes,Public_Transportation,Obesity_Type_I
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2106,20.976842,Female,1.710730,131.408528,Sometimes,yes,3.0,3.0,no,no,1.728139,yes,1.676269,0.906247,Sometimes,Public_Transportation,Obesity_Type_III
2107,21.982942,Female,1.748584,133.742943,Sometimes,yes,3.0,3.0,no,no,2.005130,yes,1.341390,0.599270,Sometimes,Public_Transportation,Obesity_Type_III
2108,22.524036,Female,1.752206,133.689352,Sometimes,yes,3.0,3.0,no,no,2.054193,yes,1.414209,0.646288,Sometimes,Public_Transportation,Obesity_Type_III
2109,24.361936,Female,1.739450,133.346641,Sometimes,yes,3.0,3.0,no,no,2.852339,yes,1.139107,0.586035,Sometimes,Public_Transportation,Obesity_Type_III
2110,23.664709,Female,1.738836,133.472641,Sometimes,yes,3.0,3.0,no,no,2.863513,yes,1.026452,0.714137,Sometimes,Public_Transportation,Obesity_Type_III

In [28]:
obesityTypeDataSet.loc[:, 'Age'] = obesityTypeDataSet['Age'].astype(int)
display(obesityTypeDataSet)

,Age,Gender,Height,Weight,CALC,FAVC,FCVC,NCP,SCC,SMOKE,CH2O,family_history_with_overweight,FAF,TUE,CAEC,MTRANS,NObeyesdad
10,26,Male,1.850000,105.000000,Sometimes,yes,3.0,3.0,no,no,3.000000,yes,2.000000,2.000000,Frequently,Public_Transportation,Obesity_Type_I
13,41,Male,1.800000,99.000000,Frequently,yes,2.0,3.0,no,no,2.000000,no,2.000000,1.000000,Sometimes,Automobile,Obesity_Type_I
17,29,Female,1.530000,78.000000,no,yes,2.0,1.0,no,no,2.000000,no,0.000000,0.000000,Sometimes,Automobile,Obesity_Type_I
21,52,Female,1.690000,87.000000,no,yes,3.0,1.0,no,yes,2.000000,yes,0.000000,0.000000,Sometimes,Automobile,Obesity_Type_I
23,22,Female,1.600000,82.000000,Sometimes,yes,1.0,1.0,no,no,2.000000,yes,0.000000,2.000000,Sometimes,Public_Transportation,Obesity_Type_I
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2106,20,Female,1.710730,131.408528,Sometimes,yes,3.0,3.0,no,no,1.728139,yes,1.676269,0.906247,Sometimes,Public_Transportation,Obesity_Type_III
2107,21,Female,1.748584,133.742943,Sometimes,yes,3.0,3.0,no,no,2.005130,yes,1.341390,0.599270,Sometimes,Public_Transportation,Obesity_Type_III
2108,22,Female,1.752206,133.689352,Sometimes,yes,3.0,3.0,no,no,2.054193,yes,1.414209,0.646288,Sometimes,Public_Transportation,Obesity_Type_III
2109,24,Female,1.739450,133.346641,Sometimes,yes,3.0,3.0,no,no,2.852339,yes,1.139107,0.586035,Sometimes,Public_Transportation,Obesity_Type_III
2110,23,Female,1.738836,133.472641,Sometimes,yes,3.0,3.0,no,no,2.863513,yes,1.026452,0.714137,Sometimes,Public_Transportation,Obesity_Type_III

In [29]:
obesityLevel_I = obesityTypeDataSet.loc[obesityTypeDataSet['NObeyesdad'] == 'Obesity_Type_I']
display(obesityLevel_I)

,Age,Gender,Height,Weight,CALC,FAVC,FCVC,NCP,SCC,SMOKE,CH2O,family_history_with_overweight,FAF,TUE,CAEC,MTRANS,NObeyesdad
10,26,Male,1.850000,105.000000,Sometimes,yes,3.000000,3.000000,no,no,3.000000,yes,2.000000,2.000000,Frequently,Public_Transportation,Obesity_Type_I
13,41,Male,1.800000,99.000000,Frequently,yes,2.000000,3.000000,no,no,2.000000,no,2.000000,1.000000,Sometimes,Automobile,Obesity_Type_I
17,29,Female,1.530000,78.000000,no,yes,2.000000,1.000000,no,no,2.000000,no,0.000000,0.000000,Sometimes,Automobile,Obesity_Type_I
21,52,Female,1.690000,87.000000,no,yes,3.000000,1.000000,no,yes,2.000000,yes,0.000000,0.000000,Sometimes,Automobile,Obesity_Type_I
23,22,Female,1.600000,82.000000,Sometimes,yes,1.000000,1.000000,no,no,2.000000,yes,0.000000,2.000000,Sometimes,Public_Transportation,Obesity_Type_I
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1508,20,Male,1.705304,99.873716,no,yes,2.000000,1.293342,no,no,2.000000,yes,0.000000,1.917679,Sometimes,Public_Transportation,Obesity_Type_I
1509,19,Female,1.612910,82.193405,no,yes,1.261288,2.930044,no,no,1.166655,yes,0.133398,0.951740,Sometimes,Public_Transportation,Obesity_Type_I
1510,18,Female,1.605469,82.039000,no,yes,2.765330,3.000000,no,no,1.048584,yes,0.192559,0.720411,Sometimes,Public_Transportation,Obesity_Type_I
1511,18,Male,1.804160,104.406820,no,yes,2.000000,3.000000,no,no,3.000000,yes,2.240500,0.000000,Sometimes,Public_Transportation,Obesity_Type_I
1512,19,Male,1.785062,104.187314,no,yes,2.000000,3.000000,no,no,2.151570,yes,1.605983,0.000000,Sometimes,Public_Transportation,Obesity_Type_I

In [33]:
mean_age_male_Obesity_I = obesityLevel_I.loc[obesityLevel_I['Gender'] == 'Male', 'Age'].mean()


mean_age_female_Obesity_I = obesityLevel_I.loc[obesityLevel_I['Gender'] == 'Female', 'Age'].mean()

print("Média de idade entre homens:", mean_age_male_Obesity_I)
print("Média de idade entre mulheres:", mean_age_female_Obesity_I)

Média de idade entre homens: 24.87457627118644
Média de idade entre mulheres: 23.353211009174313