In [19]:
import pandas as pd
import numpy as np

In [2]:
obesityDataSet = pd.read_csv('ObesityDataSet_raw_and_data_sinthetic.csv', sep=',')

obesityDataSet.shape

(2111, 17)

In [3]:
obesityDataSet.head

<bound method NDFrame.head of             Age  Gender    Height      Weight        CALC FAVC  FCVC  NCP  \
0     21.000000  Female  1.620000   64.000000          no   no   2.0  3.0
1     21.000000  Female  1.520000   56.000000   Sometimes   no   3.0  3.0
2     23.000000    Male  1.800000   77.000000  Frequently   no   2.0  3.0
3     27.000000    Male  1.800000   87.000000  Frequently   no   3.0  3.0
4     22.000000    Male  1.780000   89.800000   Sometimes   no   2.0  1.0
...         ...     ...       ...         ...         ...  ...   ...  ...
2106  20.976842  Female  1.710730  131.408528   Sometimes  yes   3.0  3.0
2107  21.982942  Female  1.748584  133.742943   Sometimes  yes   3.0  3.0
2108  22.524036  Female  1.752206  133.689352   Sometimes  yes   3.0  3.0
2109  24.361936  Female  1.739450  133.346641   Sometimes  yes   3.0  3.0
2110  23.664709  Female  1.738836  133.472641   Sometimes  yes   3.0  3.0

      SCC SMOKE      CH2O family_history_with_overweight       FAF       TUE  \
0      no    no  2.000000                            yes  0.000000  1.000000
1     yes   yes  3.000000                            yes  3.000000  0.000000
2      no    no  2.000000                            yes  2.000000  1.000000
3      no    no  2.000000                             no  2.000000  0.000000
4      no    no  2.000000                             no  0.000000  0.000000
...   ...   ...       ...                            ...       ...       ...
2106   no    no  1.728139                            yes  1.676269  0.906247
2107   no    no  2.005130                            yes  1.341390  0.599270
2108   no    no  2.054193                            yes  1.414209  0.646288
2109   no    no  2.852339                            yes  1.139107  0.586035
2110   no    no  2.863513                            yes  1.026452  0.714137

           CAEC                 MTRANS           NObeyesdad
0     Sometimes  Public_Transportation        Normal_Weight
1     Sometimes  Public_Transportation        Normal_Weight
2     Sometimes  Public_Transportation        Normal_Weight
3     Sometimes                Walking   Overweight_Level_I
4     Sometimes  Public_Transportation  Overweight_Level_II
...         ...                    ...                  ...
2106  Sometimes  Public_Transportation     Obesity_Type_III
2107  Sometimes  Public_Transportation     Obesity_Type_III
2108  Sometimes  Public_Transportation     Obesity_Type_III
2109  Sometimes  Public_Transportation     Obesity_Type_III
2110  Sometimes  Public_Transportation     Obesity_Type_III

[2111 rows x 17 columns]>

In [4]:
display(obesityDataSet)

obesityDataSet.dtypes

,Age,Gender,Height,Weight,CALC,FAVC,FCVC,NCP,SCC,SMOKE,CH2O,family_history_with_overweight,FAF,TUE,CAEC,MTRANS,NObeyesdad
0,21.000000,Female,1.620000,64.000000,no,no,2.0,3.0,no,no,2.000000,yes,0.000000,1.000000,Sometimes,Public_Transportation,Normal_Weight
1,21.000000,Female,1.520000,56.000000,Sometimes,no,3.0,3.0,yes,yes,3.000000,yes,3.000000,0.000000,Sometimes,Public_Transportation,Normal_Weight
2,23.000000,Male,1.800000,77.000000,Frequently,no,2.0,3.0,no,no,2.000000,yes,2.000000,1.000000,Sometimes,Public_Transportation,Normal_Weight
3,27.000000,Male,1.800000,87.000000,Frequently,no,3.0,3.0,no,no,2.000000,no,2.000000,0.000000,Sometimes,Walking,Overweight_Level_I
4,22.000000,Male,1.780000,89.800000,Sometimes,no,2.0,1.0,no,no,2.000000,no,0.000000,0.000000,Sometimes,Public_Transportation,Overweight_Level_II
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2106,20.976842,Female,1.710730,131.408528,Sometimes,yes,3.0,3.0,no,no,1.728139,yes,1.676269,0.906247,Sometimes,Public_Transportation,Obesity_Type_III
2107,21.982942,Female,1.748584,133.742943,Sometimes,yes,3.0,3.0,no,no,2.005130,yes,1.341390,0.599270,Sometimes,Public_Transportation,Obesity_Type_III
2108,22.524036,Female,1.752206,133.689352,Sometimes,yes,3.0,3.0,no,no,2.054193,yes,1.414209,0.646288,Sometimes,Public_Transportation,Obesity_Type_III
2109,24.361936,Female,1.739450,133.346641,Sometimes,yes,3.0,3.0,no,no,2.852339,yes,1.139107,0.586035,Sometimes,Public_Transportation,Obesity_Type_III
2110,23.664709,Female,1.738836,133.472641,Sometimes,yes,3.0,3.0,no,no,2.863513,yes,1.026452,0.714137,Sometimes,Public_Transportation,Obesity_Type_III

Age                               float64
Gender                             object
Height                            float64
Weight                            float64
CALC                               object
FAVC                               object
FCVC                              float64
NCP                               float64
SCC                                object
SMOKE                              object
CH2O                              float64
family_history_with_overweight     object
FAF                               float64
TUE                               float64
CAEC                               object
MTRANS                             object
NObeyesdad                         object
dtype: object

In [5]:
obesityDataSet.isnull().sum()

Age                               0
Gender                            0
Height                            0
Weight                            0
CALC                              0
FAVC                              0
FCVC                              0
NCP                               0
SCC                               0
SMOKE                             0
CH2O                              0
family_history_with_overweight    0
FAF                               0
TUE                               0
CAEC                              0
MTRANS                            0
NObeyesdad                        0
dtype: int64

In [6]:
obesityTypeDataSet = obesityDataSet.loc[(obesityDataSet['NObeyesdad'] != 'Normal_Weight') & (obesityDataSet['NObeyesdad'] != 'Overweight_Level_I') & (obesityDataSet['NObeyesdad'] != 'Overweight_Level_I') & (obesityDataSet['NObeyesdad'] != 'Overweight_Level_II')]
display(obesityTypeDataSet)

,Age,Gender,Height,Weight,CALC,FAVC,FCVC,NCP,SCC,SMOKE,CH2O,family_history_with_overweight,FAF,TUE,CAEC,MTRANS,NObeyesdad
10,26.000000,Male,1.850000,105.000000,Sometimes,yes,3.0,3.0,no,no,3.000000,yes,2.000000,2.000000,Frequently,Public_Transportation,Obesity_Type_I
13,41.000000,Male,1.800000,99.000000,Frequently,yes,2.0,3.0,no,no,2.000000,no,2.000000,1.000000,Sometimes,Automobile,Obesity_Type_I
17,29.000000,Female,1.530000,78.000000,no,yes,2.0,1.0,no,no,2.000000,no,0.000000,0.000000,Sometimes,Automobile,Obesity_Type_I
21,52.000000,Female,1.690000,87.000000,no,yes,3.0,1.0,no,yes,2.000000,yes,0.000000,0.000000,Sometimes,Automobile,Obesity_Type_I
23,22.000000,Female,1.600000,82.000000,Sometimes,yes,1.0,1.0,no,no,2.000000,yes,0.000000,2.000000,Sometimes,Public_Transportation,Obesity_Type_I
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2106,20.976842,Female,1.710730,131.408528,Sometimes,yes,3.0,3.0,no,no,1.728139,yes,1.676269,0.906247,Sometimes,Public_Transportation,Obesity_Type_III
2107,21.982942,Female,1.748584,133.742943,Sometimes,yes,3.0,3.0,no,no,2.005130,yes,1.341390,0.599270,Sometimes,Public_Transportation,Obesity_Type_III
2108,22.524036,Female,1.752206,133.689352,Sometimes,yes,3.0,3.0,no,no,2.054193,yes,1.414209,0.646288,Sometimes,Public_Transportation,Obesity_Type_III
2109,24.361936,Female,1.739450,133.346641,Sometimes,yes,3.0,3.0,no,no,2.852339,yes,1.139107,0.586035,Sometimes,Public_Transportation,Obesity_Type_III
2110,23.664709,Female,1.738836,133.472641,Sometimes,yes,3.0,3.0,no,no,2.863513,yes,1.026452,0.714137,Sometimes,Public_Transportation,Obesity_Type_III

In [15]:
obesityTypeDataSet.loc[:,'imc'] = (obesityTypeDataSet['Weight']) / (obesityTypeDataSet['Height'] ** 2)

display(obesityTypeDataSet)

,Age,Gender,Height,Weight,CALC,FAVC,FCVC,NCP,SCC,SMOKE,CH2O,family_history_with_overweight,FAF,TUE,CAEC,MTRANS,NObeyesdad,imc
10,26.0,Male,1.850000,105.000000,Sometimes,yes,3.0,3.0,no,no,3.000000,yes,2.000000,2.000000,Frequently,Public_Transportation,Obesity_Type_I,30.679328
13,41.0,Male,1.800000,99.000000,Frequently,yes,2.0,3.0,no,no,2.000000,no,2.000000,1.000000,Sometimes,Automobile,Obesity_Type_I,30.555556
17,29.0,Female,1.530000,78.000000,no,yes,2.0,1.0,no,no,2.000000,no,0.000000,0.000000,Sometimes,Automobile,Obesity_Type_I,33.320518
21,52.0,Female,1.690000,87.000000,no,yes,3.0,1.0,no,yes,2.000000,yes,0.000000,0.000000,Sometimes,Automobile,Obesity_Type_I,30.461118
23,22.0,Female,1.600000,82.000000,Sometimes,yes,1.0,1.0,no,no,2.000000,yes,0.000000,2.000000,Sometimes,Public_Transportation,Obesity_Type_I,32.031250
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2106,20.0,Female,1.710730,131.408528,Sometimes,yes,3.0,3.0,no,no,1.728139,yes,1.676269,0.906247,Sometimes,Public_Transportation,Obesity_Type_III,44.901475
2107,21.0,Female,1.748584,133.742943,Sometimes,yes,3.0,3.0,no,no,2.005130,yes,1.341390,0.599270,Sometimes,Public_Transportation,Obesity_Type_III,43.741923
2108,22.0,Female,1.752206,133.689352,Sometimes,yes,3.0,3.0,no,no,2.054193,yes,1.414209,0.646288,Sometimes,Public_Transportation,Obesity_Type_III,43.543817
2109,24.0,Female,1.739450,133.346641,Sometimes,yes,3.0,3.0,no,no,2.852339,yes,1.139107,0.586035,Sometimes,Public_Transportation,Obesity_Type_III,44.071535
2110,23.0,Female,1.738836,133.472641,Sometimes,yes,3.0,3.0,no,no,2.863513,yes,1.026452,0.714137,Sometimes,Public_Transportation,Obesity_Type_III,44.144338

In [8]:
obesityTypeDataSet.loc[:, 'Age'] = obesityTypeDataSet['Age'].astype(int)
display(obesityTypeDataSet)

,Age,Gender,Height,Weight,CALC,FAVC,FCVC,NCP,SCC,SMOKE,CH2O,family_history_with_overweight,FAF,TUE,CAEC,MTRANS,NObeyesdad,imc
10,26.0,Male,1.850000,105.000000,Sometimes,yes,3.0,3.0,no,no,3.000000,yes,2.000000,2.000000,Frequently,Public_Transportation,Obesity_Type_I,30.679328
13,41.0,Male,1.800000,99.000000,Frequently,yes,2.0,3.0,no,no,2.000000,no,2.000000,1.000000,Sometimes,Automobile,Obesity_Type_I,30.555556
17,29.0,Female,1.530000,78.000000,no,yes,2.0,1.0,no,no,2.000000,no,0.000000,0.000000,Sometimes,Automobile,Obesity_Type_I,33.320518
21,52.0,Female,1.690000,87.000000,no,yes,3.0,1.0,no,yes,2.000000,yes,0.000000,0.000000,Sometimes,Automobile,Obesity_Type_I,30.461118
23,22.0,Female,1.600000,82.000000,Sometimes,yes,1.0,1.0,no,no,2.000000,yes,0.000000,2.000000,Sometimes,Public_Transportation,Obesity_Type_I,32.031250
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2106,20.0,Female,1.710730,131.408528,Sometimes,yes,3.0,3.0,no,no,1.728139,yes,1.676269,0.906247,Sometimes,Public_Transportation,Obesity_Type_III,44.901475
2107,21.0,Female,1.748584,133.742943,Sometimes,yes,3.0,3.0,no,no,2.005130,yes,1.341390,0.599270,Sometimes,Public_Transportation,Obesity_Type_III,43.741923
2108,22.0,Female,1.752206,133.689352,Sometimes,yes,3.0,3.0,no,no,2.054193,yes,1.414209,0.646288,Sometimes,Public_Transportation,Obesity_Type_III,43.543817
2109,24.0,Female,1.739450,133.346641,Sometimes,yes,3.0,3.0,no,no,2.852339,yes,1.139107,0.586035,Sometimes,Public_Transportation,Obesity_Type_III,44.071535
2110,23.0,Female,1.738836,133.472641,Sometimes,yes,3.0,3.0,no,no,2.863513,yes,1.026452,0.714137,Sometimes,Public_Transportation,Obesity_Type_III,44.144338

In [9]:
obesityLevel_I = obesityTypeDataSet.loc[obesityTypeDataSet['NObeyesdad'] == 'Obesity_Type_I']
display(obesityLevel_I)

,Age,Gender,Height,Weight,CALC,FAVC,FCVC,NCP,SCC,SMOKE,CH2O,family_history_with_overweight,FAF,TUE,CAEC,MTRANS,NObeyesdad,imc
10,26.0,Male,1.850000,105.000000,Sometimes,yes,3.000000,3.000000,no,no,3.000000,yes,2.000000,2.000000,Frequently,Public_Transportation,Obesity_Type_I,30.679328
13,41.0,Male,1.800000,99.000000,Frequently,yes,2.000000,3.000000,no,no,2.000000,no,2.000000,1.000000,Sometimes,Automobile,Obesity_Type_I,30.555556
17,29.0,Female,1.530000,78.000000,no,yes,2.000000,1.000000,no,no,2.000000,no,0.000000,0.000000,Sometimes,Automobile,Obesity_Type_I,33.320518
21,52.0,Female,1.690000,87.000000,no,yes,3.000000,1.000000,no,yes,2.000000,yes,0.000000,0.000000,Sometimes,Automobile,Obesity_Type_I,30.461118
23,22.0,Female,1.600000,82.000000,Sometimes,yes,1.000000,1.000000,no,no,2.000000,yes,0.000000,2.000000,Sometimes,Public_Transportation,Obesity_Type_I,32.031250
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1508,20.0,Male,1.705304,99.873716,no,yes,2.000000,1.293342,no,no,2.000000,yes,0.000000,1.917679,Sometimes,Public_Transportation,Obesity_Type_I,34.343740
1509,19.0,Female,1.612910,82.193405,no,yes,1.261288,2.930044,no,no,1.166655,yes,0.133398,0.951740,Sometimes,Public_Transportation,Obesity_Type_I,31.594879
1510,18.0,Female,1.605469,82.039000,no,yes,2.765330,3.000000,no,no,1.048584,yes,0.192559,0.720411,Sometimes,Public_Transportation,Obesity_Type_I,31.828525
1511,18.0,Male,1.804160,104.406820,no,yes,2.000000,3.000000,no,no,3.000000,yes,2.240500,0.000000,Sometimes,Public_Transportation,Obesity_Type_I,32.075894
1512,19.0,Male,1.785062,104.187314,no,yes,2.000000,3.000000,no,no,2.151570,yes,1.605983,0.000000,Sometimes,Public_Transportation,Obesity_Type_I,32.697024

In [10]:
mean_age_male_Obesity_I = obesityLevel_I.loc[obesityLevel_I['Gender'] == 'Male', 'Age'].mean().astype(int)


mean_age_female_Obesity_I = obesityLevel_I.loc[obesityLevel_I['Gender'] == 'Female', 'Age'].mean().astype(int)

print("Média de idade entre homens:", mean_age_male_Obesity_I)
print("Média de idade entre mulheres:", mean_age_female_Obesity_I)

Média de idade entre homens: 23
Média de idade entre mulheres: 27

In [11]:
obesityLevel_II = obesityTypeDataSet.loc[obesityTypeDataSet['NObeyesdad'] == 'Obesity_Type_II']
display(obesityLevel_II)

,Age,Gender,Height,Weight,CALC,FAVC,FCVC,NCP,SCC,SMOKE,CH2O,family_history_with_overweight,FAF,TUE,CAEC,MTRANS,NObeyesdad,imc
68,30.0,Male,1.760000,112.000000,Frequently,yes,1.000000,3.000000,yes,yes,2.000000,yes,0.000000,0.000000,no,Automobile,Obesity_Type_II,36.157025
90,25.0,Female,1.630000,93.000000,no,no,3.000000,4.000000,no,no,1.000000,no,2.000000,0.000000,Always,Public_Transportation,Obesity_Type_II,35.003199
165,30.0,Male,1.920000,130.000000,Sometimes,no,2.000000,3.000000,no,yes,1.000000,yes,1.000000,0.000000,Sometimes,Public_Transportation,Obesity_Type_II,35.264757
197,41.0,Male,1.750000,118.000000,Sometimes,yes,2.000000,3.000000,no,no,2.000000,yes,0.000000,0.000000,Sometimes,Bike,Obesity_Type_II,38.530612
210,20.0,Male,1.800000,114.000000,no,yes,2.000000,3.000000,no,no,2.000000,yes,0.000000,1.000000,Frequently,Public_Transportation,Obesity_Type_II,35.185185
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1794,30.0,Male,1.653876,102.583895,no,yes,2.919526,2.142328,no,no,1.175714,yes,0.958555,0.636289,Sometimes,Public_Transportation,Obesity_Type_II,37.503629
1795,20.0,Male,1.657132,105.580491,no,yes,2.724121,1.437959,no,no,1.590418,yes,0.029603,1.122118,Sometimes,Public_Transportation,Obesity_Type_II,38.447621
1796,20.0,Male,1.644751,101.067988,no,yes,2.801992,1.343117,no,no,1.128942,yes,0.233987,0.819980,Sometimes,Public_Transportation,Obesity_Type_II,37.360554
1797,25.0,Male,1.660761,104.321463,no,yes,2.748971,1.213431,no,no,1.448875,yes,0.128548,1.239038,Sometimes,Public_Transportation,Obesity_Type_II,37.823298
1798,26.0,Male,1.691510,102.595180,no,yes,2.680375,1.089048,no,no,1.366238,yes,0.181324,1.041677,Sometimes,Public_Transportation,Obesity_Type_II,35.857319

In [12]:
mean_age_male_Obesity_II = obesityLevel_II.loc[obesityLevel_II['Gender'] == 'Male', 'Age'].mean().astype(int)


mean_age_female_Obesity_II = obesityLevel_II.loc[obesityLevel_II['Gender'] == 'Female', 'Age'].mean().astype(int)

print("Média de idade entre homens:", mean_age_male_Obesity_II)
print("Média de idade entre mulheres:", mean_age_female_Obesity_II)

Média de idade entre homens: 27
Média de idade entre mulheres: 24

In [13]:
obesityLevel_III = obesityTypeDataSet.loc[obesityTypeDataSet['NObeyesdad'] == 'Obesity_Type_III']
display(obesityLevel_III)

,Age,Gender,Height,Weight,CALC,FAVC,FCVC,NCP,SCC,SMOKE,CH2O,family_history_with_overweight,FAF,TUE,CAEC,MTRANS,NObeyesdad,imc
202,26.0,Female,1.560000,102.000000,Sometimes,yes,3.0,3.0,no,yes,1.000000,yes,0.000000,1.000000,Sometimes,Public_Transportation,Obesity_Type_III,41.913215
344,18.0,Male,1.870000,173.000000,Sometimes,yes,3.0,3.0,no,no,2.000000,yes,2.000000,1.000000,Frequently,Public_Transportation,Obesity_Type_III,49.472390
403,26.0,Female,1.660000,112.000000,no,no,3.0,3.0,no,no,3.000000,yes,0.000000,0.000000,Sometimes,Automobile,Obesity_Type_III,40.644506
498,25.0,Female,1.686306,104.572712,Sometimes,yes,3.0,3.0,no,no,1.152736,yes,0.319156,1.000000,Sometimes,Public_Transportation,Obesity_Type_III,36.774400
499,18.0,Female,1.683124,126.673780,Sometimes,yes,3.0,3.0,no,no,1.115967,yes,1.541072,1.000000,Sometimes,Public_Transportation,Obesity_Type_III,44.715131
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2106,20.0,Female,1.710730,131.408528,Sometimes,yes,3.0,3.0,no,no,1.728139,yes,1.676269,0.906247,Sometimes,Public_Transportation,Obesity_Type_III,44.901475
2107,21.0,Female,1.748584,133.742943,Sometimes,yes,3.0,3.0,no,no,2.005130,yes,1.341390,0.599270,Sometimes,Public_Transportation,Obesity_Type_III,43.741923
2108,22.0,Female,1.752206,133.689352,Sometimes,yes,3.0,3.0,no,no,2.054193,yes,1.414209,0.646288,Sometimes,Public_Transportation,Obesity_Type_III,43.543817
2109,24.0,Female,1.739450,133.346641,Sometimes,yes,3.0,3.0,no,no,2.852339,yes,1.139107,0.586035,Sometimes,Public_Transportation,Obesity_Type_III,44.071535
2110,23.0,Female,1.738836,133.472641,Sometimes,yes,3.0,3.0,no,no,2.863513,yes,1.026452,0.714137,Sometimes,Public_Transportation,Obesity_Type_III,44.144338

In [14]:
mean_age_male_Obesity_III = obesityLevel_III.loc[obesityLevel_III['Gender'] == 'Male', 'Age'].mean().astype(int)


mean_age_female_Obesity_III = obesityLevel_III.loc[obesityLevel_III['Gender'] == 'Female', 'Age'].mean().astype(int)

print("Média de idade entre homens:", mean_age_male_Obesity_III)
print("Média de idade entre mulheres:", mean_age_female_Obesity_III)

Média de idade entre homens: 18
Média de idade entre mulheres: 23

In [23]:
mean_obesityData_Man = obesityTypeDataSet.loc[obesityTypeDataSet['Gender'] == 'Male', 'Age'].mean()

mean_obesityData_Woman = obesityTypeDataSet.loc[obesityTypeDataSet['Gender'] == 'Female', 'Age'].mean()


print("Man mean",mean_obesityData_Man)

print("Woman mean",mean_obesityData_Woman)


median_man = np.median(obesityTypeDataSet.loc[obesityTypeDataSet['Gender'] == 'Male', 'Age'])
median_woman = np.median(obesityTypeDataSet.loc[obesityTypeDataSet['Gender'] == 'Female', 'Age'])


print("Man median",mean_obesityData_Man)

print("Woman median",median_woman)

# Ambos os casos mostram que a média é maior do que a mediana. Isso sugere que pode haver alguns valores extremos de idade
# mais altos que estão puxando a média para cima em ambos os grupos (homens e mulheres). Esses valores extremos podem 
# representar uma pequena porcentagem da população, enquanto a maioria das idades está abaixo da média.

Man mean 24.87457627118644
Woman mean 23.353211009174313
Man median 24.87457627118644
Woman median 22.0

In [27]:
consumo_de_Alimentos_e_habitos = obesityTypeDataSet[['Age', 'Gender', 'FAVC', 'FCVC', 'NCP', 'family_history_with_overweight', 'imc', 'NObeyesdad']]

display(consumo_de_Alimentos_e_habitos)

,Age,Gender,FAVC,FCVC,NCP,family_history_with_overweight,imc,NObeyesdad
10,26.0,Male,yes,3.0,3.0,yes,30.679328,Obesity_Type_I
13,41.0,Male,yes,2.0,3.0,no,30.555556,Obesity_Type_I
17,29.0,Female,yes,2.0,1.0,no,33.320518,Obesity_Type_I
21,52.0,Female,yes,3.0,1.0,yes,30.461118,Obesity_Type_I
23,22.0,Female,yes,1.0,1.0,yes,32.031250,Obesity_Type_I
...,...,...,...,...,...,...,...,...
2106,20.0,Female,yes,3.0,3.0,yes,44.901475,Obesity_Type_III
2107,21.0,Female,yes,3.0,3.0,yes,43.741923,Obesity_Type_III
2108,22.0,Female,yes,3.0,3.0,yes,43.543817,Obesity_Type_III
2109,24.0,Female,yes,3.0,3.0,yes,44.071535,Obesity_Type_III
2110,23.0,Female,yes,3.0,3.0,yes,44.144338,Obesity_Type_III